### ISSUE TITLE
1.16.2 Nether creative crash

### ISSUE THREAD

**Issue by Gomez96** [Globox1997/BootZ#2]
When I'm in the Nether while wearing Netherite Reinforced boots and using creative mode then it crashes:

 The game crashed whilst exception while ticking
Error: java.lang.StackOverflowError: Exception while ticking
Exit Code: -1

 Here's the entire log: https://pastebin.com/etes9fCL

**Comment by Globox1997** [comment]
The crash doesn't occur due to bootz
